### ISSUE TITLE
BST Zone causes nil for Date parsing

### ISSUE THREAD

**Issue by SalahEddin** [AdeptusAstartes/AlamofireRSSParser#1]

**Comment by dangelillo-newsela** [comment]
It wouldn't be the time zone that causes it.  It would have to have something to do with the date format.  The feed you're trying to parse must be using a non-standard date format.

**Comment by SalahEddin** [comment]
I added an 'if' in the source that instead "xxx xx xx z" it parses the pattern "xxx xx xx 'BST'" and it works.
