### ISSUE TITLE
Xcode 11.3 Module file's minimum deployment target error

### ISSUE THREAD

**Issue by Momeks** [AdeptusAstartes/AlamofireRSSParser#12]
I am using AlamofireRSSParser, today I’ve got a strange error, which did not happen before, the compiler gives me this error while I am trying to install the app on my device or simulator:

> Compiling for iOS 8.0, but module 'Alamofire' has a minimum deployment target of iOS 10.0

I tried to change AlamofireRSSParser minimum deployment target to iOS 10 but got new errors!
Deleting DerivedData folder, clean and build, and updating pods did not help. How can I fix this error?

**Comment by Momeks** [comment]
I downgraded Alamofire to 4.9.2 and the problem fixed.

**Comment by jminutaglio** [comment]
I had the same compile error.  

I wasn't able to find a downgraded Alamofire 4.9.2, but was able to work around this issue with a downgrade of Alamofire to 4.9.1.

`pod 'Alamofire', '~> 4.9.1'`

**Comment by AdeptusAstartes** [comment]
This is because the previous version was not compatible with Alamofire 5 (both the code and more importantly the dependencies).  If you would like to use Alamofire 5 please update to AlamafireRSSParser 2.3.0.
